# Generated by Django 4.0 on 2022-06-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_created_on_post_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
